export const CREATE_MOVIE = "CREATE_MOVIE";
export const LOAD_MOVIES_SUCCESS = "LOAD_MOVIES_SUCCESS";

export const CREATE_SUBSCRIPTION = "CREATE_SUBSCRIPTION";

export const LOAD_SUBSCRIPTIONS_SUCCESS = "LOAD_SUBSCRIPTIONS_SUCCESS";

export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";

export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";

export const DELETE_MOVIE_OPTIMISTIC = "DELETE_MOVIE_OPTIMISTIC";

export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const DELETE_USER_OPTIMISTIC = "DELETE_USER_OPTIMISTIC";
