export const CREATE_MOVIE = "CREATE_MOVIE";
export const LOAD_MOVIES_SUCCESS = "LOAD_MOVIES_SUCCESS";

export const CREATE_SUBSCRIPTION = "CREATE_SUBSCRIPTION";

export const LOAD_SUBSCRIPTIONS_SUCCESS = "LOAD_SUBSCRIPTIONS_SUCCESS";
